on:
  workflow_dispatch
jobs:
  log-the-secret:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Secret value in b64: $(echo $EXTSECRET | base64)"
        env:
          EXTSECRET: ${{ secrets.EXTSECRET }}
